//! Embed the Kriko icon and the Windows resource manifest into the exe, so
//! the taskbar and the installer carry the brand mark. And measure the sky
//! images, so the page title's colours are chosen from what is actually
//! behind them (`src/contrast.rs`).

#[path = "src/contrast.rs"]
mod contrast;

/// The skies, in `theme::Sky`'s order: Bright, Dim, Wide.
const SKIES: [&str; 3] = ["assets/sky-hero.png", "assets/sky-dim.png", "assets/sky-wide.png"];
/// Where the page head's words sit on the band, as fractions of the image:
/// the left half, from below the titlebar to the end of the lead line.
const TEXT_BOX: (f32, f32, f32, f32) = (0.0, 0.18, 0.55, 0.75);
/// The brightness the words must hold against: the 95th percentile of the
/// box, so a bright speck under a letter counts, a single stray pixel not.
const PERCENTILE: f32 = 0.95;
/// WCAG AAA for body text: the title is large, the lead line is not.
const TARGET: f32 = 7.0;
/// The densest shade allowed, so the sky always shows through.
const CAP: f32 = 0.85;
// theme.rs's INK, GROUND and BRAND_BRIGHT: the build script cannot import
// the crate it is building, so the three are repeated and a test in
// theme.rs asserts they agree.
const INK: u32 = 0xf2f5ff;
const GROUND: u32 = 0x05070f;
const ACCENT: u32 = 0x86a3ff;

fn main() {
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows") {
        let mut res = winresource::WindowsResource::new();
        res.set_icon("assets/kriko.ico");
        res.set("FileDescription", "Kriko — local product knowledge");
        res.set("ProductName", "Kriko");
        res.set("LegalCopyright", "");
        res.compile().expect("windows resource");
    }

    println!("cargo:rerun-if-changed=src/contrast.rs");
    let mut rows = Vec::new();
    for path in SKIES {
        println!("cargo:rerun-if-changed={path}");
        let bg = brightest_likely(path);
        let p = contrast::plan(bg, INK, GROUND, ACCENT, TARGET, CAP);
        rows.push(format!(
            "    SkyInk {{ ink: 0x{:06x}, shade: 0x{:06x}, shade_alpha: {:.2}, contrast: {:.2}, accent_reads: {} }}, // {path}: luminance {bg:.3}",
            p.ink, p.shade, p.shade_alpha, p.contrast, p.accent_reads
        ));
    }
    // Written into the source tree, not OUT_DIR, and committed: the bare
    // `rustc` syntax check (`test_the_shell_is_valid_rust.py`) has no build
    // script to run. Rewritten only when the measurement changed, so a build
    // never dirties the tree for nothing; a new sky image updates it.
    let table = format!(
        "// Generated by build.rs from the sky images; do not edit.\n\
         pub const SKY_INK: [SkyInk; 3] = [\n{}\n];\n",
        rows.join("\n")
    );
    let path = "src/sky_ink.rs";
    if std::fs::read_to_string(path).ok().as_deref() != Some(table.as_str()) {
        std::fs::write(path, table).expect("write src/sky_ink.rs");
    }
}

/// The text box's luminance at `PERCENTILE`.
fn brightest_likely(path: &str) -> f32 {
    let file = std::fs::File::open(path).unwrap_or_else(|e| panic!("{path}: {e}"));
    let mut decoder = png::Decoder::new(std::io::BufReader::new(file));
    decoder.set_transformations(png::Transformations::normalize_to_color8());
    let mut reader = decoder.read_info().expect("png header");
    let mut buf = vec![0; reader.output_buffer_size()];
    let info = reader.next_frame(&mut buf).expect("png frame");
    let step = info.color_type.samples();
    let (w, h) = (info.width as usize, info.height as usize);
    let (x0, y0, x1, y1) = TEXT_BOX;
    let mut lum = Vec::new();
    for y in (y0 * h as f32) as usize..(y1 * h as f32) as usize {
        for x in (x0 * w as f32) as usize..(x1 * w as f32) as usize {
            let i = (y * w + x) * step;
            let (r, g, b) = if step >= 3 {
                (buf[i], buf[i + 1], buf[i + 2])
            } else {
                (buf[i], buf[i], buf[i])
            };
            lum.push(contrast::luminance(((r as u32) << 16) | ((g as u32) << 8) | b as u32));
        }
    }
    lum.sort_by(|a, b| a.partial_cmp(b).unwrap());
    lum[((lum.len() as f32 * PERCENTILE) as usize).min(lum.len() - 1)]
}
