// Generated by build.rs from the sky images; do not edit.
pub const SKY_INK: [SkyInk; 3] = [
    SkyInk { ink: 0xf2f5ff, shade: 0x05070f, shade_alpha: 0.34, contrast: 7.03, accent_reads: false }, // assets/sky-hero.png: luminance 0.131
    SkyInk { ink: 0xf2f5ff, shade: 0x05070f, shade_alpha: 0.34, contrast: 7.03, accent_reads: false }, // assets/sky-dim.png: luminance 0.131
    SkyInk { ink: 0xf2f5ff, shade: 0x05070f, shade_alpha: 0.34, contrast: 7.03, accent_reads: false }, // assets/sky-wide.png: luminance 0.131
];
