"""Draw the horizontal lockup and its monochrome twin from the mark's own grid.

`extension/assets/logo-mark.svg` is the product's letter. A lockup is that
letter beside the word, and the word has to be drawn in the same language or
the two halves read as a logo somebody put next to a font.

**So the wordmark is not set in a typeface.** It is built from the same cell
grid, the same 3-cell stroke and the same 14-cell cap height as the mark. That
buys three things a font would not: it renders identically everywhere with no
`@font-face` and no network, it cannot drift when the app's display face
changes, and it is unmistakably the same object as the icon — which is the one
job a lockup has.

Two files come out, and the second is not a colour variant of the first:

- `logo-lockup.svg` — the real thing, on the panel's ground.
- `logo-lockup-mono.svg` — one colour, no ground, `currentColor`. For a
  favicon strip, a README, an invoice, anywhere the ground is not ours.

    python packaging/render_lockup.py

Checked by `src/app/tests/test_brand_lockup.py`, which regenerates and compares
— editing the SVG by hand fails, the same way it does for the icon.
"""

import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MARK = REPO / "extension" / "assets" / "logo-mark.svg"
LOCKUP = REPO / "extension" / "assets" / "logo-lockup.svg"
MONO = REPO / "extension" / "assets" / "logo-lockup-mono.svg"

GROUND, INK, ACCENT = "#15171C", "#E7E9ED", "#E8C04B"

#: Cap height and stroke, in cells. Both are read off the mark rather than
#: chosen: its stem is 14 tall and 3 wide, so the word sits at the same weight
#: and the same height as the letter beside it.
CAP, STROKE = 14, 3
#: Between letters. One stroke — tight enough that the word is a block at small
#: sizes, which is what a slab wordmark is for.
TRACK = 3
#: Between the mark and the word. Wider than the tracking on purpose: at a
#: normal gap the eye reads the mark as the word's first letter and the
#: wordmark becomes "KKriko".
GAP = 10

#: Each letter as (width, blocks), blocks being (x, y, w, h) in cells with the
#: cap's top-left as the origin. Five glyphs, because the product is called one
#: thing — a general alphabet here would be a typeface nobody asked for.
GLYPHS: dict[str, tuple[int, list[tuple[int, int, int, int]]]] = {
    # The mark's own letterform in ink: stem, then three blocks stepping away
    # from it in each direction, overlapping by two rows so the staircase is
    # one stroke.
    "K": (12, [(0, 0, 3, 14),
               (3, 4, 3, 4), (6, 2, 3, 4), (9, 0, 3, 4),
               (3, 6, 3, 4), (6, 8, 3, 4), (9, 10, 3, 4)]),
    # Bowl closed over three rows of counter, then the leg steps out in two.
    "R": (11, [(0, 0, 3, 14),
               (3, 0, 5, 3), (8, 0, 3, 9), (3, 6, 5, 3),
               (5, 9, 3, 3), (8, 11, 3, 3)]),
    "I": (3, [(0, 0, 3, 14)]),
    "O": (11, [(0, 0, 3, 14), (8, 0, 3, 14), (3, 0, 5, 3), (3, 11, 5, 3)]),
}

WORD = "KRIKO"


def mark_blocks() -> list[tuple[int, int, int, int, str]]:
    """The mark's own rects, read out of the mark rather than repeated here.

    A second copy of those coordinates is a second drawing, which is the whole
    failure `render_icon.py` exists to prevent. The ground rect is dropped —
    the lockup paints its own, wider one.
    """
    found = re.findall(
        r'<rect\s+x="(\d+)"\s+y="(\d+)"\s+width="(\d+)"\s+height="(\d+)"'
        r'\s+fill="(#[0-9A-Fa-f]{6})"',
        MARK.read_text(encoding="utf-8"),
    )
    return [(int(x), int(y), int(w), int(h), fill.upper())
            for x, y, w, h, fill in found
            if not (int(w) == 16 and int(h) == 16)]


def word_blocks(x0: int, y0: int) -> tuple[list[tuple[int, int, int, int]], int]:
    out: list[tuple[int, int, int, int]] = []
    x = x0
    for letter in WORD:
        wide, blocks = GLYPHS[letter]
        out += [(x + bx, y0 + by, bw, bh) for bx, by, bw, bh in blocks]
        x += wide + TRACK
    return out, x - TRACK - x0


def render() -> tuple[str, str]:
    letters, wide = word_blocks(16 + GAP, 1)
    width = 16 + GAP + wide + 2
    rects = [f'  <rect x="{x}" y="{y}" width="{w}" height="{h}" fill="{fill}"></rect>'
             for x, y, w, h, fill in mark_blocks()]
    rects += [f'  <rect x="{x}" y="{y}" width="{w}" height="{h}" fill="{INK}"></rect>'
              for x, y, w, h in letters]

    head = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} 16"'
            f' shape-rendering="crispEdges" role="img" aria-label="Kriko">\n'
            f'  <!-- Generated by packaging/render_lockup.py — do not edit by\n'
            f'       hand. The mark is read out of logo-mark.svg, so it cannot\n'
            f'       drift from the icon; the word is drawn on the same grid at\n'
            f'       the same cap height and stroke. -->\n')
    full = (head
            + f'  <rect x="0" y="0" width="{width}" height="16" fill="{GROUND}"></rect>\n'
            + "\n".join(rects) + "\n</svg>\n")

    mono_rects = [
        f'  <rect x="{x}" y="{y}" width="{w}" height="{h}" fill="currentColor"></rect>'
        for x, y, w, h, _ in mark_blocks()
    ] + [
        f'  <rect x="{x}" y="{y}" width="{w}" height="{h}" fill="currentColor"></rect>'
        for x, y, w, h in letters
    ]
    mono = (head.replace("aria-label=\"Kriko\"", "aria-label=\"Kriko\"")
            + "\n".join(mono_rects) + "\n</svg>\n")
    return full, mono


def main() -> None:
    full, mono = render()
    LOCKUP.write_text(full, encoding="utf-8")
    MONO.write_text(mono, encoding="utf-8")
    print(f"{MARK.name} + {WORD} -> {LOCKUP}")
    print(f"{MARK.name} + {WORD} -> {MONO}")


if __name__ == "__main__":
    main()
