"""One palette, two vocabularies, and now a generator between them.

`ui/src/styles/themes/panel.css` and `extension/hover_lite/hover_lite.css`
describe the same colours under different names. That is not an accident and it
is not a mistake: the app's palette is a neutral *ramp* (`--n-0` … `--n-9`)
that its components speak in aliases, and the panel needs names for the five
surfaces it actually has. Two vocabularies for one palette is the
right design.

**What was wrong is that nothing kept them equal.** 38 tokens one side, 28 the
other, exactly two names in both, and the translation written as a *comment* in
`panel.css`:

    --n-2: #15171c; /* --bg-panel  — cards, the rail */

A correspondence a person maintains is a bug waiting. This repository has caught
that shape four times already — `SIBLING_CODE_FAMILIES` going stale, `_MAKE_MAP`
in Python, the site's own words in the extension, and now the palette — and each
time the fix was to derive the thing rather than to write it down twice.

So the comment becomes the mechanism. `MAP` below is the translation, in code,
and `tools/gate.sh` fails when the emitted block and the committed one differ.

    python tools/tokens.py           # write
    python tools/tokens.py --check   # fail if the committed block is stale

**The first run produced no diff**, which was the whole reason to build this
now rather than after something moved: all ten mapped greys still agreed
exactly, so an empty diff proved the map was transcribed correctly. That proof
was available exactly once.

The app owns the palette, and the arrow points that way for two reasons. It is
the fuller vocabulary (a ramp, where the panel has five named surfaces), and
`docs/BRAND.md` already makes `panel.css` the owner of the three colours the
mark is drawn in. (There was a third reason until B159: the app was where a
theme was *chosen*, and `slate` and `lemonade` had no meaning inside a content
script. Panel is the only theme now.) A second owner would have
the mark answering to one file and the panel to another.

Only colour is generated. Type and motion stay hand-written on both sides:
the panel deliberately names no font it might fetch, and the two easing curves
differ because they are tuned to different motions — a panel sliding in over
somebody's page, and a view changing inside a window.
"""

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "ui" / "src" / "styles" / "themes" / "panel.css"
TARGET = REPO / "extension" / "hover_lite" / "hover_lite.css"
#: Every sheet that carries the block. The panel first; the extension's
#: settings page wears the same palette since it took the design system, so
#: it gets the same block rather than a second hand-kept copy.
TARGETS = (TARGET, REPO / "extension" / "options" / "options.css")

BEGIN = "  /* BEGIN generated by tools/tokens.py — do not edit */"
END = "  /* END generated by tools/tokens.py */"

#: The translation, as data. Each row is one line of the emitted block:
#: (the extension's name, the app's name, the heading it sits under).
#:
#: `bg-item` and `border-soft` are here because the app gained them *for* this:
#: they are a row inside a card and a rule inside a card, two surfaces the panel
#: has always had and the app had no name for. Adding them to the source was
#: cheaper and more honest than leaving two tokens outside the mechanism and
#: calling the palette shared.
MAP: tuple[tuple[str, str, str], ...] = (
    ("bg-base", "n-0", "Dark palette"),
    ("bg-panel", "n-2", ""),
    ("bg-header", "n-1", ""),
    ("bg-surface", "n-3", ""),
    ("bg-item", "panel-item", ""),
    ("border", "n-4", ""),
    ("border-soft", "line-soft", ""),
    ("fg", "n-9", "Text"),
    ("fg-body", "n-8", ""),
    ("fg-muted", "n-7", ""),
    ("fg-subtle", "n-6", ""),
    ("fg-faint", "n-5", ""),
)

#: The design system's own tokens: the brand key, ice for what is live, the
#: LED dot, the bezel of a plate, the glass of a card, the well a tile sits
#: in. Same name on both sides, because the panel adopted the app's words
#: when it took the app's look, so there is nothing to translate; they are
#: listed so the panel cannot drift from the app in exactly the colours that
#: make it look like the app. Aliases (`--well: var(--n-3)`) are resolved.
DESIGN: tuple[str, ...] = (
    "brand", "brand-hover", "brand-low", "brand-bright", "on-brand",
    "ice", "led-off", "led-dim",
    "bezel-hi", "bezel-lo", "bezel-edge",
    "glass-1", "glass-2", "glass-3",
    "well", "border-control",
)

#: Severity, which is the one place the two sides had genuinely different
#: *shapes* rather than different names. The app hand-mixed an opaque fill per
#: severity (`--high-soft: #2a1719`) and had no border token at all; the panel
#: derived both from the ink with alpha. The panel's is better — a fourth
#: severity costs it one value and costs the app three — so the derivation
#: lives here and both sides get the same three per severity.
#:
#: (the extension's prefix, the app's ink token)
SEVERITY: tuple[tuple[str, str], ...] = (
    ("high", "high"),
    ("med", "medium"),
    ("low", "low"),
)
#: How far over the ground a severity fill and its edge sit. Two numbers rather
#: than six hand-mixed values, which is the entire point of deriving them.
FILL_ALPHA, EDGE_ALPHA = "0.10", "0.30"

#: Where the value column starts, so the emitted block reads as a table rather
#: than as output. Cosmetic, and cosmetic is why anybody would edit it by hand.
COLUMN = 17


def declared(css: str) -> dict[str, str]:
    """Every `--name: value;` in the source, by name.

    Deliberately a regular expression rather than a CSS parser: the source is
    one flat block of custom properties, and a parser would be a dependency
    the build does not otherwise have. A source that outgrows this should get
    the parser, not a cleverer pattern.
    """
    return {
        name: value.strip()
        for name, value in re.findall(r"^\s*--([a-z0-9-]+):\s*([^;]+);", css, re.M)
    }


def rgb(value: str) -> tuple[int, int, int]:
    text = value.strip().lstrip("#")
    if len(text) == 3:
        text = "".join(one * 2 for one in text)
    if len(text) != 6:
        raise ValueError(f"not a hex colour: {value!r}")
    return tuple(int(text[i:i + 2], 16) for i in (0, 2, 4))  # type: ignore[return-value]


def _resolved(have: dict[str, str], value: str, depth: int = 0) -> str:
    """The literal a `var(--name)` alias settles on.

    The panel is free to answer a token with another token — `--accent` is
    `var(--ice)` since the rebuild — and this has to hand the panel's *colour*
    across, because the panel declares no aliases of its own. `depth` is a
    guard, not a budget: an alias chain that loops resolves to the value rather
    than hanging the build, and a chain longer than a couple of hops is a
    palette nobody could follow by hand anyway.
    """
    text = value.strip()
    if not text.startswith("var(") or depth > 8:
        return text
    name = text.removeprefix("var(").removesuffix(")").strip().removeprefix("--")
    if name not in have:
        # An alias to something the panel does not declare is a typo, and
        # emitting it would push the same typo into a second file.
        raise SystemExit(
            f"{SOURCE.name} answers {value!r} with a token it never declares: "
            f"--{name}"
        )
    return _resolved(have, have[name], depth + 1)


def _line(name: str, value: str) -> str:
    head = f"  --{name}:"
    return f"{head}{' ' * max(1, COLUMN - len(head))}{value};"


def block(css: str) -> str:
    """The extension's colour tokens, from the app's."""
    have = declared(css)
    missing = [app for _, app, _ in MAP if app not in have]
    missing += [app for _, app in SEVERITY if app not in have]
    missing += [name for name in DESIGN if name not in have]
    if missing:
        raise SystemExit(
            f"{SOURCE.name} declares no " + ", ".join(f"--{one}" for one in missing)
            + " — the map in tools/tokens.py names a token the palette does not"
        )

    out = [BEGIN]
    for mine, theirs, heading in MAP:
        if heading:
            out.append("" if len(out) > 1 else "")
            out.append(f"  /* {heading} */")
        out.append(_line(mine, have[theirs]))

    out.append("")
    out.append("  /* Severity — surface and edge derived from the ink, so a")
    out.append("     fourth one costs a single value rather than three. */")
    for prefix, ink in SEVERITY:
        red, green, blue = rgb(have[ink])
        out.append(_line(f"{prefix}-surface", f"rgba({red},{green},{blue},{FILL_ALPHA})"))
        out.append(_line(f"{prefix}-border", f"rgba({red},{green},{blue},{EDGE_ALPHA})"))
        out.append(_line(f"{prefix}-ink", have[ink]))

    out.append("")
    out.append("  /* Design system: brand, ice, LED, bezel, glass, well */")
    for name in DESIGN:
        out.append(_line(name, _resolved(have, have[name])))

    out.append("")
    # Accent is resolved rather than copied, because the panel answers it
    # with an alias. Copying `var(--ice)` across leaves the panel naming a
    # token it does not declare, and every one of its 23 `var(--accent)` uses
    # resolves to nothing: the hover card's one accent colour, gone, with
    # the generated block still matching its source byte for byte. A
    # generated block that agrees with its generator is not the same as a
    # working one.
    out.append("  /* Accent, resolved from the panel's alias */")
    out.append(_line("accent", _resolved(have, have["accent"])))
    out.append(END)
    return "\n".join(out)


def rewritten(target: str, generated: str) -> str:
    start = target.index(BEGIN)
    end = target.index(END) + len(END)
    return target[:start] + generated + target[end:]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed block is not what this writes")
    args = parser.parse_args()

    generated = block(SOURCE.read_text(encoding="utf-8"))
    stale = 0
    for path in TARGETS:
        target = path.read_text(encoding="utf-8")
        if BEGIN not in target or END not in target:
            raise SystemExit(
                f"{path.relative_to(REPO)} has no generated block. Put\n"
                f"{BEGIN}\n{END}\naround its colour tokens and run this again."
            )
        updated = rewritten(target, generated)
        if args.check:
            if updated != target:
                print(
                    f"{path.relative_to(REPO)} is stale — its palette no longer "
                    f"matches {SOURCE.relative_to(REPO)}.\n"
                    f"Run `python tools/tokens.py` and commit the result.",
                    file=sys.stderr,
                )
                stale += 1
            else:
                print(f"{path.relative_to(REPO)} matches {SOURCE.relative_to(REPO)}")
            continue
        path.write_text(updated, encoding="utf-8")
        print(f"{SOURCE.relative_to(REPO)} -> {path.relative_to(REPO)}")
    return 1 if stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
